dataset:
  source: MOT17
  sequence: MOT17-02-FRCNN
  path: data/MOT17/train/MOT17-04-FRCNN/img1
  max_frames: 1050
models:
  available:
  - yolov8n
  - yolov8s
  - yolov8m
  - yolov8l
  - yolov8x
  starting_model: yolov8n
  parameters:
    yolov8n: 3.2
    yolov8s: 11.2
    yolov8m: 25.9
    yolov8l: 43.7
    yolov8x: 68.2
  colors:
    yolov8n:
    - 0
    - 255
    - 0
    yolov8s:
    - 0
    - 255
    - 255
    yolov8m:
    - 255
    - 165
    - 0
    yolov8l:
    - 255
    - 0
    - 255
    yolov8x:
    - 255
    - 0
    - 0
object_selection:
  strategy: high_confidence
  target_confidence: 0.8
  specific_object_id: null
adaptive_thresholds:
  confidence_levels:
    very_high: 0.85
    high: 0.7
    medium: 0.5
    low: 0.35
    very_low: 0.25
  uncertainty:
    variance_threshold: 0.15
    smoothing_window: 5
  hysteresis:
    frames_before_switch: 3
    cooldown_frames: 10
tracking:
  iou_threshold: 0.3
  max_lost_frames: 5
  confidence_threshold: 0.25
visualization:
  generate_video: true
  output_video_path: results/adaptive/MOT17-04_adaptive_tracking_1050frames.mp4
  fps: 30
  show_confidence: true
  show_model_name: true
  show_fps: true
  show_uncertainty: true
  font_scale: 0.7
  box_thickness: 3
  text_color:
  - 255
  - 255
  - 255
output:
  results_dir: results/adaptive
  save_metrics: true
  save_frame_data: true
  generate_plots: true
  markdown_report: results/adaptive/ADAPTIVE_TRACKING_RESULTS.md
